# Generated by Django 5.0 on 2023-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_legal_entity', models.CharField(max_length=255)),
                ('ogrn', models.IntegerField(max_length=15)),
                ('legal_address', models.CharField(max_length=255)),
                ('inn', models.IntegerField(max_length=12)),
                ('kpp', models.IntegerField(max_length=9)),
                ('bank', models.CharField(max_length=255)),
                ('p_s', models.IntegerField(max_length=20)),
                ('k_s', models.IntegerField(max_length=20)),
                ('bik', models.IntegerField(max_length=9)),
            ],
        ),
    ]
